### ISSUE TITLE
執行結束之後結果殘留的 temp.txt 中，而非 proxies.txt 中

### ISSUE THREAD

**Issue by namiwang** [0xHJK/Proxies#1]
the title says it all

**Comment by 0xHJK** [comment]
所有爬下来的代理会保存在temp.txt，已检测可用的代理会保存到proxies.txt

**Comment by haha517** [comment]
Missing dependencies for SOCKS support

**Comment by 0xHJK** [comment]
@haha517 You should use socks proxy first, such as [shadowsocks](https://github.com/shadowsocks/)
