### ISSUE TITLE
大佬，有效性测出来了，要怎么测速度呢

### ISSUE THREAD

**Issue by jianfei96** [0xHJK/Proxies#4]
如题，拿来给pymusic-dl当代理，随手挑一个都是慢如老牛拉车

**Comment by 0xHJK** [comment]
取检测完的代理，改一改代码，指定一个音乐下载链接批量跑一下试试

**Comment by jianfei96** [comment]
> 取检测完的代理，改一改代码，指定一个音乐下载链接批量跑一下试试

emmm，我也希望我会改
不管怎么样还是谢大佬
